version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - CI=true npm run test
      - npm run build
      - sls package
      - echo "serverless pacakge done" 
      - cd .serverless
      - pwd
      - aws s3 cp frontend-experiment.zip s3://frontend-experiment/
    
artifacts:
  files:
    - '**/*'
  base-directory: build