version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - CI=true npm run test
      - npm run build
      - serverless package
      - echo "serverless pacakge done" 
      - cd .serverless
      - pwd
      - ls
      - aws s3 cp frontend-experiment.zip s3://frontend-experiment/
    
artifacts:
  files:
    - '**/*'
  base-directory: build